ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_MAX_EMAIL_ADDRESSES = 1
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_USER_MODEL_USERNAME_FIELD = None

# Enable later
ACCOUNT_EMAIL_NOTIFICATIONS = False
ACCOUNT_EMAIL_VERIFICATION = "none"

ACCOUNT_FORMS = {
    "signup": "accounts.forms.CustomSignupForm",
}
